# Generated by Django 3.1 on 2020-08-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0002_auto_20200829_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.story'),
            preserve_default=False,
        ),
    ]
