# Generated by Django 3.1 on 2020-08-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0003_auto_20200829_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='answer_text',
        ),
    ]
