# Generated by Django 3.1 on 2020-08-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0005_auto_20200829_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choice_five',
        ),
    ]
