# Generated by Django 3.1 on 2020-08-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0007_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(max_length=10000),
        ),
    ]
