# Generated by Django 3.1 on 2020-08-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0010_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Maximum Marks'),
        ),
    ]
